#Tests all test cases for rsruby

require 'test/unit'

require 'tc_attributes'
require 'tc_cliques'
require 'tc_create'
require 'tc_add_delete'
require 'tc_basic_query'
require 'tc_basic_properties'
require 'tc_centrality'
require 'tc_components'
require 'tc_copy'
require 'tc_cores'
require 'tc_dijkstra'
require 'tc_directedness'
require 'tc_error_handling'
require 'tc_file_read_write'
require 'tc_independent_vertex_sets'
require 'tc_isomorphic'
require 'tc_iterators'
require 'tc_layout'
require 'tc_matrix'
require 'tc_motif'
require 'tc_other_ops'
require 'tc_selectors'
require 'tc_shortest_paths'
require 'tc_spanning'
require 'tc_spectral'
require 'tc_topological_sort'
require 'tc_transitivity'
require 'tc_vertex_neighbourhood'
